routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('auth')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/pilih-toko/{id_toko}', [App\Http\Controllers\HomeController::class, 'pilihToko'])->name('pilih-toko');
Route::get('/lupakan-toko/', [App\Http\Controllers\HomeController::class, 'lupakanSessionToko'])->name('lupakan-toko');
Route::get('/nasabah/{id}/riwayat-gadai', [App\Http\Controllers\Admin\NasabahController::class, 'showRiwayatGadai'])->name('nasabah.riwayat-gadai');
Route::post('/transaksi-gadai/{id_detail_transaksi}/pembayaran', [App\Http\Controllers\Admin\TransaksiGadaiController::class, 'pembayaran'])->name('transaksi-gadai.pembayaran');
Route::get('/transaksi-gadai/{id_detail_transaksi}/download-nota/', [App\Http\Controllers\Admin\TransaksiGadaiController::class, 'downloadNota'])->name('transaksi-gadai.download-nota');
Route::get('/kode_penghapusan', [App\Http\Controllers\Admin\KodePenghapusanController::class, 'index'])->name('kode_penghapusan.index');
Route::get('/toko/edit-modal/{id}', [App\Http\Controllers\Admin\TokoController::class, 'editModal'])->name('toko.edit-modal');
Route::post('/toko/update-modal/{id}', [App\Http\Controllers\Admin\TokoController::class, 'updateModal'])->name('toko.update-modal');

Route::resource('/nasabah', App\Http\Controllers\Admin\NasabahController::class);
Route::resource('/transaksi-gadai', App\Http\Controllers\Admin\TransaksiGadaiController::class);
Route::resource('/bunga', App\Http\Controllers\Admin\BungaController::class);
Route::resource('/toko', App\Http\Controllers\Admin\TokoController::class);
Route::resource('/dana-nasabah', App\Http\Controllers\Admin\DanaNasabahController::class);
Route::resource('/arus-uang-pusat', App\Http\Controllers\Admin\ArusUangPusatController::class);

app/Models/DanaNasabah.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DanaNasabah extends Model
{
    use HasFactory;

    protected $table = "dana_nasabah";

    public function nasabah()
    {
        return $this->hasOne(Nasabah::class, 'id', 'nasabah_id');
    }
}

app/Http/Controllers/Admin/DanaNasabahController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\DanaNasabah;
use App\Models\Nasabah;
use App\Models\Toko;
use Illuminate\Http\Request;

class DanaNasabahController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $dana_nasabahs = DanaNasabah::all();
        return view('admin.dana_nasabah.index', compact('dana_nasabahs'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $nasabahs = Nasabah::all();
        $tokos = Toko::all();
        return view('admin.dana_nasabah.create', compact('nasabahs', 'tokos'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $newDanaNasabah = new DanaNasabah();
        $newDanaNasabah->nasabah_id = $request->nasabah_id;
        $newDanaNasabah->toko_id = $request->toko_id;
        $newDanaNasabah->jumlah = $request->jumlah_dana;
        $newDanaNasabah->bunga = $request->bunga;

        $newDanaNasabah->save();

        return redirect()->back()->with('success', 'Berhasil menambah data baru!');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/dana_nasabah/create.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Tambah Dana Nasabah</h3>
                    <form class="forms-sample" method="POST" action="{{ route('dana-nasabah.store') }}"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="toko_id">Toko</label>
                            <select name="toko_id" id="toko_id" class="form-control">
                                @foreach ($tokos as $toko)
                                    @if (session()->has('id_toko') && $toko->id == session()->get('id_toko'))
                                        <option value="{{ $toko->id }}" selected>{{ $toko->nama }}</option>
                                    @else
                                        <option value="{{ $toko->id }}">{{ $toko->nama }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="nasabah_id">Nama</label>
                            <select name="nasabah_id" id="nasabah_id" class="form-control">
                                @foreach ($nasabahs as $nasabah)
                                    <option value="{{ $nasabah->id }}">{{ $nasabah->nama }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="jumlah_dana">Jumlah Dana</label>
                            <input type="text" class="form-control" id="jumlah_dana" placeholder="Jumlah Dana"
                                name="jumlah_dana">
                        </div>
                        <div class="form-group">
                            <label for="bunga">Bunga</label>
                            <input type="text" class="form-control" id="bunga" placeholder="Bunga" name="bunga">
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/dana_nasabah/index.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Daftar Dana Nasabah</h3>
                <a class="btn btn-primary" href="{{route('dana-nasabah.create')}}">Tambah Dana Nasabah</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Jumlah</th>
                            <th>Bunga</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($dana_nasabahs as $dana_nasabah)
                            <tr>
                                <td>{{$dana_nasabah->nasabah->nama}}</td>
                                <td>Rp. {{number_format($dana_nasabah->jumlah)}}</td>
                                <td>{{$dana_nasabah->bunga}} %</td>
                               
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/dana_nasabah/riwayat-gadai.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Daftar Riwayat Gadai</h3>
                <div class="form-group">
                    <label>Nama : {{$nasabah->nama}}</label>
                    <br>
                    <label>Nomor Identitas : {{$nasabah->nomor_identitas}}</label>
                    <br>
                    <label>Telp : {{$nasabah->telp}}</label>
                    <br>
                    <label>Alamat : {{$nasabah->alamat}}</label>
                </div>
                <hr>
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tanggal Gadai</th>
                            <th>Tanggal Pelunasan</th>
                            <th>Gramasi</th>
                            <th>Kadar</th>
                            <th>Nominal</th>
                            <th>Bunga</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($nasabah->transaksiGadai as $transaksi)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{date('d M Y', strtotime($transaksi->created_at))}}</td>
                                <td>{{date('d M Y', strtotime($transaksi->deadline))}}</td>
                                <td>{{ $transaksi->gramasi }} gr</td>
                                <td>{{ $transaksi->kadar }} karat</td>
                                <td>Rp. {{ number_format($transaksi->nilai_pinjaman) }}</td>
                                <td>{{ $transaksi->bunga }} %</td>
                            </tr>
                        @endforeach
                    </tbody>
            </div>
        </div>
    </div>
</div>
@endsection