routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('auth')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/pilih-toko/{id_toko}', [App\Http\Controllers\HomeController::class, 'pilihToko'])->name('pilih-toko');
Route::get('/lupakan-toko/', [App\Http\Controllers\HomeController::class, 'lupakanSessionToko'])->name('lupakan-toko');
Route::get('/nasabah/{id}/riwayat-gadai', [App\Http\Controllers\Admin\NasabahController::class, 'showRiwayatGadai'])->name('nasabah.riwayat-gadai');
Route::post('/transaksi-gadai/{id_detail_transaksi}/pembayaran', [App\Http\Controllers\Admin\TransaksiGadaiController::class, 'pembayaran'])->name('transaksi-gadai.pembayaran');
Route::get('/transaksi-gadai/{id_detail_transaksi}/download-nota/', [App\Http\Controllers\Admin\TransaksiGadaiController::class, 'downloadNota'])->name('transaksi-gadai.download-nota');
Route::get('/kode_penghapusan', [App\Http\Controllers\Admin\KodePenghapusanController::class, 'index'])->name('kode_penghapusan.index');
Route::get('/toko/edit-modal/{id}', [App\Http\Controllers\Admin\TokoController::class, 'editModal'])->name('toko.edit-modal');
Route::post('/toko/update-modal/{id}', [App\Http\Controllers\Admin\TokoController::class, 'updateModal'])->name('toko.update-modal');

Route::resource('/nasabah', App\Http\Controllers\Admin\NasabahController::class);
Route::resource('/transaksi-gadai', App\Http\Controllers\Admin\TransaksiGadaiController::class);
Route::resource('/bunga', App\Http\Controllers\Admin\BungaController::class);
Route::resource('/toko', App\Http\Controllers\Admin\TokoController::class);
Route::resource('/dana-nasabah', App\Http\Controllers\Admin\DanaNasabahController::class);
Route::resource('/arus-uang-pusat', App\Http\Controllers\Admin\ArusUangPusatController::class);

app/Models/TransaksiGadai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

class TransaksiGadai extends Model
{
    use HasFactory;

    protected $table = "transaksi_gadai";

    /**
     * Get the nasabah associated with the TransaksiGadai
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function nasabah(): HasOne
    {
        return $this->hasOne(Nasabah::class, 'id', 'nasabah_id');
    }

    public function detail()
    {
        return $this->hasMany(DetailTransaksiGadai::class, 'transaksi_gadai_id', 'id');
    }
}

app/Http/Controllers/Admin/TransaksiGadaiController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\DetailTransaksiGadai;
use App\Models\Nasabah;
use App\Models\Toko;
use App\Models\TransaksiGadai;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf as DomPDF;

class TransaksiGadaiController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $id = $request->toko_id;
        $transaksis = new TransaksiGadai();

        if($request->cari_gramasi)
        {
            $transaksis = $transaksis->where('gramasi', $request->cari_gramasi);
        }

        if($request->cari_kadar)
        {
            $transaksis = $transaksis->where('kadar', $request->cari_kadar);
        }

        if($id != null)
        {
            $transaksis = $transaksis->where('toko_id', $id)->get();
            $toko = Toko::find($id);
            return view('admin.transaksi-gadai.index', compact('transaksis', 'toko'));
        }
        elseif(session()->has('id_toko'))
        {
            $transaksis = $transaksis->where('toko_id', session()->get('id_toko'))->get();
            return view('admin.transaksi-gadai.index', compact('transaksis'));
        }
        else 
        {
            $transaksis = $transaksis->get();
            return view('admin.transaksi-gadai.index', compact('transaksis'));
        }
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $nasabahs = Nasabah::all();
        $tokos = Toko::all();
        return view('admin.transaksi-gadai.create', compact('nasabahs', 'tokos'));
        
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $newTransaksiGadai = new TransaksiGadai();
        $newTransaksiGadai->nasabah_id = $request->nasabah_id;
        $newTransaksiGadai->toko_id = $request->toko_id;
        $newTransaksiGadai->gramasi = $request->gramasi;
        $newTransaksiGadai->kadar = $request->kadar;
        $newTransaksiGadai->nilai_pinjaman = $request->nilai_pinjaman;
        $newTransaksiGadai->sisa_pinjaman = $request->nilai_pinjaman;
        $newTransaksiGadai->bunga = $request->bunga;
        if(auth()->user()->hasRole('owner'))
        {
            $newTransaksiGadai->tanggal_gadai = $request->tanggal_gadai;
        } else {
            $newTransaksiGadai->tanggal_gadai = date('Y-m-d', strtotime(now()));
        }

        if(($request->file('foto_produk') != null))
        {
            $name = rand().time().'.'.$request->foto_produk->extension();
            $request->foto_produk->move(public_path('foto_produk'), $name);
            $newTransaksiGadai->foto_produk = "foto_produk/".$name;
        } else {
            return redirect()->back()->with('error', 'Mohon isi foto produk!');
        }

        $newTransaksiGadai->save();

        $newDetailTransaksiGadai = new DetailTransaksiGadai();
        $newDetailTransaksiGadai->transaksi_gadai_id = $newTransaksiGadai->id;
        $newDetailTransaksiGadai->cicilan_ke = 1;
        $newDetailTransaksiGadai->persen_bunga = $request->bunga;

        if($request->nilai_pinjaman >= 1000000) {
            $jumlahBunga = $request->bunga / 100 * $request->nilai_pinjaman;
        } else {
            $jumlahBunga = $request->bunga / 100 * 1000000;
        }
        $biayaAdmin = 0;
        $totalBiaya = $jumlahBunga / 12 + $newTransaksiGadai->nilai_pinjaman / 12 + $biayaAdmin;

        $newDetailTransaksiGadai->jumlah_bunga = $jumlahBunga;
        $newDetailTransaksiGadai->biaya_admin = $biayaAdmin;
        $newDetailTransaksiGadai->total_biaya = $totalBiaya;
        $newDetailTransaksiGadai->sisa_pinjaman = $newTransaksiGadai->nilai_pinjaman;
        $newDetailTransaksiGadai->status = 'BELUM TERBAYAR';
        $newDetailTransaksiGadai->save();

        return redirect()->back()->with('success', 'Berhasil menambah data baru!');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $transaksiGadai = TransaksiGadai::find($id);
        return view('admin.transaksi-gadai.detail', compact('transaksiGadai'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Request $request, $id)
    {
        $validasi = KodePenghapusanController::validasi($request->email, $request->password);
        if($validasi == true)
        {
            DetailTransaksiGadai::where('transaksi_gadai_id', $id)->delete();
            TransaksiGadai::destroy($id);
            return redirect()->back()->with('success', 'Berhasil hapus transaksi');
        }
        else
        {
            return redirect()->back()->with('error', 'Kode owner tidak sesuai!');
        }
    }

    public function pembayaran(Request $request, $id_detail_transaksi)
    {
        $detailTransaksiGadai = DetailTransaksiGadai::find($id_detail_transaksi);
        $detailTransaksiGadai->status = "TERBAYAR";
        $detailTransaksiGadai->tanggal_pelunasan = Carbon::now()->toDateString();
        $detailTransaksiGadai->total_pembayaran = $request->total_pembayaran;
        $detailTransaksiGadai->save();
        
        $sisaPinjaman = $detailTransaksiGadai->transaksiGadai->sisa_pinjaman - ($detailTransaksiGadai->total_pembayaran - $detailTransaksiGadai->jumlah_bunga / 12);

        $transaksiGadai = TransaksiGadai::find($detailTransaksiGadai->transaksiGadai->id);
        $transaksiGadai->sisa_pinjaman = $sisaPinjaman;
        $transaksiGadai->save();
        
        $newDetailTransaksiGadai = new DetailTransaksiGadai();
        $newDetailTransaksiGadai->transaksi_gadai_id = $transaksiGadai->id;
        $newDetailTransaksiGadai->cicilan_ke = $detailTransaksiGadai->cicilan_ke + 1;
        $newDetailTransaksiGadai->persen_bunga = $detailTransaksiGadai->persen_bunga;

        if($sisaPinjaman >= 1000000)
        {
            $jumlahBunga = $detailTransaksiGadai->persen_bunga / 100 * $sisaPinjaman;
        } else {
            $jumlahBunga = $detailTransaksiGadai->persen_bunga / 100 * 1000000;
        }

        $biayaAdmin = 0;
        $totalBiaya = $jumlahBunga / 12 + $sisaPinjaman / 12 + $biayaAdmin;

        $newDetailTransaksiGadai->jumlah_bunga = $jumlahBunga;
        $newDetailTransaksiGadai->biaya_admin = $biayaAdmin;
        $newDetailTransaksiGadai->total_biaya = $totalBiaya;
        $newDetailTransaksiGadai->sisa_pinjaman = $sisaPinjaman;
        $newDetailTransaksiGadai->status = 'BELUM TERBAYAR';
        $newDetailTransaksiGadai->save();

        return redirect()->back()->with('success', 'Berhasil melakukan pembayaran!');
    }

    public function downloadNota($id) {
        try {

            $detailTransaksiGadai = DetailTransaksiGadai::find($id)->toArray();
            // return view('admin.transaksi-gadai.template-nota', compact('detailTransaksiGadai'));
            $pdf = DomPDF::loadView('admin.transaksi-gadai.template-nota', compact('detailTransaksiGadai'));
            
            return $pdf->download('nota.pdf');
        } catch (\Exception $e) {
            dd($e);
            return redirect()->back()->with('error', 'Gagal print nota!');
        }
    }

}

resources/views/admin/transaksi-gadai/create.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Tambah Transaksi Gadai</h3>
                    <form class="forms-sample" method="POST" action="{{ route('transaksi-gadai.store') }}"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="toko_id">Toko</label>
                            <select name="toko_id" id="toko_id" class="form-control">
                                @foreach ($tokos as $toko)
                                    @if (session()->has('id_toko') && $toko->id == session()->get('id_toko'))
                                        <option value="{{ $toko->id }}" selected>{{ $toko->nama }}</option>
                                    @else
                                        <option value="{{ $toko->id }}">{{ $toko->nama }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="nasabah_id">Nama</label>
                            <select name="nasabah_id" id="nasabah_id" class="form-control">
                                @foreach ($nasabahs as $nasabah)
                                    <option value="{{ $nasabah->id }}">{{ $nasabah->nama }}</option>
                                @endforeach
                            </select>
                        </div>
                        @if (auth()->user()->hasRole('owner'))
                            <div class="form-group">
                                <label for="tanggal_gadai">Tanggal Gadai</label>
                                <input type="date" class="form-control" id="tanggal_gadai" name="tanggal_gadai">
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="gramasi">Gramasi</label>
                            <input type="text" class="form-control" id="gramasi" placeholder="Gramasi" name="gramasi"
                                step="0.01" min="0.01">
                        </div>
                        <div class="form-group">
                            <label for="kadar">Kadar</label>
                            <input type="text" class="form-control" id="kadar" placeholder="Kadar" name="kadar">
                        </div>
                        <div class="form-group">
                            <label for="nilai_pinjaman">Nilai Pinjaman</label>
                            <input type="text" class="form-control" id="nilai_pinjaman" placeholder="Nilai Pinjaman"
                                name="nilai_pinjaman">
                        </div>

                        <div class="form-group">
                            <label for="bunga">Bunga</label>
                            <input type="text" class="form-control" id="bunga" placeholder="Bunga" name="bunga">
                        </div>

                        <div class="form-group">
                            <label for="foto_produk">Foto Produk</label>
                            <input type="file" class="form-control" id="foto_produk" placeholder="Foto Produk"
                                name="foto_produk">
                        </div>

                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/transaksi-gadai/detail.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Detail Transaksi Gadai</h3>
                <div class="row">
                    <div class="col-6">
                        <div class="row mt-2">
                            <div class="col-8">
                                <label>Nama Nasabah : </label>
                                <input type="text" value="{{$transaksiGadai->nasabah->nama}}" class="form-control" disabled>
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-8">
                                <label>Nilai Pinjaman : </label>
                                <input type="text" value="Rp. {{number_format($transaksiGadai->nilai_pinjaman)}}" class="form-control" disabled>
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-8">
                                <label>Sisa Pinjaman : </label>
                                <input type="text" value="Rp. {{number_format($transaksiGadai->sisa_pinjaman)}}" class="form-control" disabled>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="row mt-2">
                            <div class="col-8">
                                <label>Gramasi : </label>
                                <input type="text" value="{{$transaksiGadai->gramasi}} gram" class="form-control" disabled>
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-8">
                                <label>Kadar : </label>
                                <input type="text" value="{{$transaksiGadai->kadar}} karat" class="form-control" disabled>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                <table class="table mt-4">
                    <thead>
                        <tr>
                            <th>Cicilan Ke</th>
                            <th>Persen Bunga</th>
                            <th>Jumlah Bunga Bulanan</th>
                            <th>Total Biaya</th>
                            <th>Status</th>
                            <th>Sisa Pinjaman</th>
                            <th>Pembayaran</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($transaksiGadai->detail as $detailTransaksi)
                            <tr>
                                <td>{{$detailTransaksi->cicilan_ke}}</td>
                                <td>{{$detailTransaksi->persen_bunga}} % (Rp. {{number_format($detailTransaksi->jumlah_bunga)}})</td>
                                <td>Rp. {{number_format($detailTransaksi->jumlah_bunga / 12)}}</td>
                                    @if($detailTransaksi->tanggal_pelunasan == null)
                                        <input type="hidden" value="{{$detailTransaksi->total_biaya}}" id="total_biaya_input">
                                    @endif
                                <td>
                                    Rp. {{number_format($detailTransaksi->jumlah_bunga / 12)}} (Bunga Bulanan) <br> Rp. {{number_format($detailTransaksi->sisa_pinjaman / 12)}} (Cicilan Bulanan) <br>
                                    = Rp. {{number_format($detailTransaksi->total_biaya)}}</td>
                                <td>{{$detailTransaksi->status}}</td>
                                <td>
                                    @if($detailTransaksi->sisa_pinjaman)
                                        Rp. {{number_format($detailTransaksi->sisa_pinjaman)}}</td>
                                    @else
                                    Rp. {{number_format($transaksiGadai->nilai_pinjaman)}}</td>
                                    @endif
                                <td>
                                    @if ($detailTransaksi->tanggal_pelunasan != null)
                                        {{$detailTransaksi->tanggal_pelunasan}} <br><br>
                                        Sebesar : Rp. {{number_format($detailTransaksi->total_pembayaran)}} <br><br>
                                        <a href="{{route('transaksi-gadai.download-nota', $detailTransaksi->id)}}">Cetak Nota</a>
                                    @elseif($detailTransaksi->sisa_pinjaman <= 0)
                                        Transaksi Selesai
                                    @else
                                        <form action="{{route('transaksi-gadai.pembayaran', $detailTransaksi->id)}}" method="POST">
                                            @csrf
                                            <input type="text" id="input-nominal" class="form-control mb-2" name="total_pembayaran" placeholder="Nominal Pembayaran" >
                                            {{-- <input type="hidden" id="input-total-pembayaran" name="total_pembayaran"> --}}
                                            <div>
                                                Nominal Pembayaran Minimal : Rp. {{number_format($detailTransaksi->total_biaya)}}
                                                {{-- <span>Total Pembayaran : </span>
                                                <span>{{number_format($detailTransaksi->total_biaya)}} + </span><span id="nominal_pembayaran_span">0</span> = <span id="total_pembayaran_span">0</span> --}}
                                            </div>
                                            <button type="submit" class="btn btn-primary mt-3">Pembayaran</button>
                                        </form>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

<script src="https://code.jquery.com/jquery-3.6.4.slim.js" integrity="sha256-dWvV84T6BhzO4vG6gWhsWVKVoa4lVmLnpBOZh/CAHU4=" crossorigin="anonymous"></script>
<script>

    function hitungTotalPembayaran(event) {
        const total_biaya = $('#total_biaya_input').val();
        var total_pembayaran = parseInt(event.target.value) + parseInt(total_biaya);
        // $('#nominal_pembayaran_span').html(parseInt(event.target.value).toLocaleString());
        // $('#total_pembayaran_span').html(total_pembayaran.toLocaleString());
        // $('#input-total-pembayaran').val(total_pembayaran);
    }
</script>

resources/views/admin/transaksi-gadai/index.blade.php
@extends('layout')

@section('content')
<div class="row">
    <?php
        //  dd(session()->get('id_toko')) 
         ?>
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Daftar Transaksi Gadai {{(isset($toko) ? "| Toko $toko->nama" : '')}}</h3>
                <a class="btn btn-primary" href="{{route('transaksi-gadai.create')}}">Transaksi Gadai Nasabah</a>
                <form action="{{route('transaksi-gadai.index')}}">
                    <div class="row mt-3">
                        <div class="col">
                            <input type="text" class="form-control" name="cari_nama" placeholder="Cari Nama...">
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" name="cari_gramasi" placeholder="Cari Gramasi...">
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" name="cari_kadar" placeholder="Cari Kadar...">
                        </div>
                    </div>
                    <button class="btn btn-secondary mt-1">Cari</button>
                </form>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Tanggal Mulai</th>
                            <th>Nama Nasabah</th>
                            <th>Foto Produk</th>
                            <th>Gramasi</th>
                            <th>Kadar</th>
                            <th>Nilai Pinjaman</th>
                            <th>Sisa Pinjaman</th>
                            <th>Bunga</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($transaksis as $transaksi)
                            <tr>
                                <td>{{date('d M Y', strtotime($transaksi->created_at))}}</td>
                                <td>{{$transaksi->nasabah->nama}}</td>
                                <td> <img src="{{URL::to('/').'/'.$transaksi->foto_produk}}"> </td>
                                <td>{{$transaksi->gramasi}} gr</td>
                                <td>{{$transaksi->kadar}} karat</td>
                                <td>Rp. {{number_format($transaksi->nilai_pinjaman)}}</td>
                                <td>
                                    @if ($transaksi->sisa_pinjaman >= 0)
                                    Rp. {{number_format($transaksi->sisa_pinjaman)}}
                                    @else
                                    LUNAS
                                    @endif
                                </td>
                                <td>{{$transaksi->bunga}} %</td>
                                <td>
                                    <a class="btn btn-primary" href="{{route('transaksi-gadai.show', $transaksi->id)}}">Detail</a>
                                    <button class="btn btn-danger" type="button" class="delete-btn" data-id-transaksi="{{$transaksi->id}}" data-bs-toggle="modal" data-bs-target="#deleteTransaksiModal">Hapus Transaksi</button>
                                    <div class="modal fade" id="deleteTransaksiModal" tabindex="-1" aria-labelledby="deleteTransaksiModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h3 class="modal-title" id="deleteTransaksiModalLabel">
                                                        Hapus Transaksi
                                                    </h3>
                                                    <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <form method="POST" action="{{route('transaksi-gadai.destroy', $transaksi->id)}}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <div class="form-group">
                                                            <label for="email">Email Owner :</label>
                                                            <input type="password" class="form-control" id="email" name="email" placeholder="Email Owner">
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="password">Password Owner :</label>
                                                            <input type="password" class="form-control" id="password" name="password" placeholder="Password Owner">
                                                        </div>
                                                        <button class="btn btn-danger" type="submit">Hapus Transaksi</button>
                                                    </form>
                                                </div>
                                                    <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Batal</button>
                                    
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/transaksi-gadai/template-nota.blade.php
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>A simple, clean, and responsive HTML invoice template</title>

		<style>
			.invoice-box {
				max-width: 800px;
				margin: auto;
				padding: 30px;
				border: 1px solid #eee;
				box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
				font-size: 16px;
				line-height: 24px;
				font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
				color: #555;
			}

			.invoice-box table {
				width: 100%;
				line-height: inherit;
				text-align: left;
			}

			.invoice-box table td {
				padding: 5px;
				vertical-align: top;
			}

			.invoice-box table tr td:nth-child(2) {
				text-align: right;
			}

			.invoice-box table tr.top table td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.top table td.title {
				font-size: 45px;
				line-height: 45px;
				color: #333;
			}

			.invoice-box table tr.information table td {
				padding-bottom: 40px;
			}

			.invoice-box table tr.heading td {
				background: #eee;
				border-bottom: 1px solid #ddd;
				font-weight: bold;
			}

			.invoice-box table tr.details td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.item td {
				border-bottom: 1px solid #eee;
			}

			.invoice-box table tr.item.last td {
				border-bottom: none;
			}

			.invoice-box table tr.total td:nth-child(2) {
				border-top: 2px solid #eee;
				font-weight: bold;
			}

			@media only screen and (max-width: 600px) {
				.invoice-box table tr.top table td {
					width: 100%;
					display: block;
					text-align: center;
				}

				.invoice-box table tr.information table td {
					width: 100%;
					display: block;
					text-align: center;
				}
			}

			/** RTL **/
			.invoice-box.rtl {
				direction: rtl;
				font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
			}

			.invoice-box.rtl table {
				text-align: right;
			}

			.invoice-box.rtl table tr td:nth-child(2) {
				text-align: left;
			}
		</style>
	</head>

	<body>
		<div class="invoice-box">
			<table cellpadding="0" cellspacing="0">
				<tr class="top">
					<td colspan="2">
						<table>
							<tr>
								<td class="title">
									<img src="{{public_path('logo_omega.PNG')}}" style="width: 100%; max-width: 300px" />
								</td>

								<td>
									{{-- Tanggal: {{date('d M Y', strtotime($detailTransaksiGadai['created_at']))}}<br /> --}}
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="information">
					<td colspan="2">
						<table>
							<tr>
								<td>
									{{-- Sparksuite, Inc.<br />
									12345 Sunny Road<br />
									Sunnyville, CA 12345 --}}
								</td>

								<td style="text-align: right">
									{{-- Tn./Ny./Nn.<br />
									{{$detailTransaksiGadai['nama']}}<br />
									{{$detailTransaksiGadai['telp']}} --}}
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="heading">
					<td>Cicilan Ke-</td>
                    <td>Persen Bunga</td>
					<td>Jumlah Bunga</td>
					<td>Total Biaya</td>
					<td>Total Pembayaran</td>
					<td>Sisa Pinjaman</td>
				</tr>

				<tr class="item">
					<td>{{$detailTransaksiGadai['cicilan_ke']}}</td>
					<td>{{$detailTransaksiGadai['persen_bunga']}} %</td>
					<td>Rp. {{number_format($detailTransaksiGadai['jumlah_bunga'])}}</td>
					<td>Rp. {{number_format($detailTransaksiGadai['total_biaya'])}}</td>
					<td>Rp. {{number_format($detailTransaksiGadai['total_pembayaran'])}}</td>
					<td>Rp. {{number_format($detailTransaksiGadai['sisa_pinjaman'])}}</td>
				</tr>

				<tr class="item last">
					
				</tr>
				
			</table>

            <span><b><u>PERHATIAN</u></b></span><br>
            <span>Tidak ada biaya admin.</span><br>
            <span>Gadai di bawah 1 jt dikenakan bunga 1jt/bulannya</span><br>
            <span>Nota wajib disertakan pada saat pelunasan</span>
		</div>
	</body>
</html>