routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('auth')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/pilih-toko/{id_toko}', [App\Http\Controllers\HomeController::class, 'pilihToko'])->name('pilih-toko');
Route::get('/lupakan-toko/', [App\Http\Controllers\HomeController::class, 'lupakanSessionToko'])->name('lupakan-toko');
Route::get('/nasabah/{id}/riwayat-gadai', [App\Http\Controllers\Admin\NasabahController::class, 'showRiwayatGadai'])->name('nasabah.riwayat-gadai');
Route::post('/transaksi-gadai/{id_detail_transaksi}/pembayaran', [App\Http\Controllers\Admin\TransaksiGadaiController::class, 'pembayaran'])->name('transaksi-gadai.pembayaran');
Route::get('/transaksi-gadai/{id_detail_transaksi}/download-nota/', [App\Http\Controllers\Admin\TransaksiGadaiController::class, 'downloadNota'])->name('transaksi-gadai.download-nota');
Route::get('/kode_penghapusan', [App\Http\Controllers\Admin\KodePenghapusanController::class, 'index'])->name('kode_penghapusan.index');
Route::get('/toko/edit-modal/{id}', [App\Http\Controllers\Admin\TokoController::class, 'editModal'])->name('toko.edit-modal');
Route::post('/toko/update-modal/{id}', [App\Http\Controllers\Admin\TokoController::class, 'updateModal'])->name('toko.update-modal');

Route::resource('/nasabah', App\Http\Controllers\Admin\NasabahController::class);
Route::resource('/transaksi-gadai', App\Http\Controllers\Admin\TransaksiGadaiController::class);
Route::resource('/bunga', App\Http\Controllers\Admin\BungaController::class);
Route::resource('/toko', App\Http\Controllers\Admin\TokoController::class);
Route::resource('/dana-nasabah', App\Http\Controllers\Admin\DanaNasabahController::class);
Route::resource('/arus-uang-pusat', App\Http\Controllers\Admin\ArusUangPusatController::class);

app/Models/Toko.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Toko extends Model
{
    use HasFactory;

    protected $table = "toko";
}

app/Http/Controllers/Admin/TokoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Toko;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TokoController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $tokos = Toko::all();
        return view('admin.toko.index', compact('tokos'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.toko.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        try {
            DB::beginTransaction();

            $newToko = new Toko();
            $newToko->nama = $request->nama;
            $newToko->save();

            DB::commit();

            return redirect()->back()->with('success', 'Berhasil tambah toko!');
        } catch (\Throwable $th) {
            DB::rollback();
            dd($th);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $toko = Toko::find($id);
        return view('admin.toko.show', compact('toko'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function editModal(string $id)
    {
        $toko = Toko::find($id);
        return view('admin.toko.edit-modal', compact('toko'));
    }

    public function updateModal(Request $request, string $id)
    {
        $toko = Toko::find($id);
        $toko->modal += $request->modal;
        $toko->save();
        return redirect()->back()->with('success', 'Berhasil ubah modal!');
    }
}

resources/views/admin/toko/create.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Tambah Toko</h3>
                <form class="forms-sample" method="POST" action="{{route('toko.store')}}">
                    @csrf
                    <div class="form-group">
                      <label for="nama">Nama</label>
                      <input type="text" class="form-control" id="nama" placeholder="Nama Toko" name="nama">
                    </div>
                    
                    <button type="submit" class="btn btn-primary me-2">Submit</button>
                  </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/toko/edit-modal.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Edit Modal</h3>
                <form class="forms-sample" method="POST" action="{{route('toko.update-modal', $toko->id)}}">
                    @csrf
                    <div class="form-group">
                      <label for="modal">Jumlah Modal yang Ingin Ditambah / Dikurangi</label>
                      <input type="text" class="form-control" id="modal" name="modal">
                    </div>
                    
                    <button type="submit" class="btn btn-primary me-2">Submit</button>
                  </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/toko/index.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Daftar Toko</h3>
                <a class="btn btn-primary" href="{{route('toko.create')}}">Tambah Toko</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Modal</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($tokos as $toko)
                            <tr>
                                <td>{{$toko->nama}}</td>
                                <td>Rp. {{number_format($toko->modal)}}</td>
                                <td><a href="{{route('toko.edit-modal', $toko->id)}}" class="btn btn-secondary">Edit Modal</a></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/toko/show.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Toko {{$toko->nama}}</h3>
                
            </div>
        </div>
    </div>
</div>
@endsection